# Generated by Django 3.1.3 on 2020-12-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitRequest',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('request_info', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=25)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
