# Generated by Django 3.1.3 on 2020-12-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitrequest',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
    ]
