# Generated by Django 3.1.3 on 2020-12-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_submitrequest_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('service_id', models.IntegerField()),
                ('status_description', models.CharField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
