# Generated by Django 3.1.3 on 2020-12-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_servicestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTechnician',
            fields=[
                ('serial_no', models.AutoField(primary_key=True, serialize=False)),
                ('request_info', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=25)),
                ('address_line_1', models.CharField(max_length=200)),
                ('address_line_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
                ('technician', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
