# Generated by Django 3.1.3 on 2020-12-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_assigntechnician'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntechnician',
            name='request_id',
            field=models.IntegerField(null=True),
        ),
    ]
