# Generated by Django 3.1.3 on 2021-01-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
